[phases.setup]
nixPkgs = ["python39", "python39Packages.pip"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn -w 1 --threads 4 -b 0.0.0.0:$PORT kalshi_bot.web:app"
